server:
  port: 8765

eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user-service/api/v1/user/**, /user-service/api/v1/role/**
            filters:
              - RewritePath=/user-service/?(?<segment>.*), /$\{segment}
          - id: task-service
            uri: lb://task-service
            predicates:
              - Path=/task-service/api/v1/project/**, /task-service/api/v1/issue/**, /task-service/api/v1/user/**
            filters:
              - RewritePath=/task-service/?(?<segment>.*), /$\{segment}
