server:
  port: 0

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
