server:
  port: 0

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user-topic: user-topic
    consumer:
      group-id: task-service
      auto-offset-reset: earliest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    #      properties:
    #        spring.deserializer:
    #          value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    #        spring.json.trusted.packages: "org.example.userservice.entity.dto, org.example.taskservice.entity.dto, java.util"

    listener:
      missing-topics-fatal: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
