server:
  port: 8080

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://db:5432/task_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    topic:
      user-topic: user-topic
    consumer:
      group-id: task-service
      auto-offset-reset: earliest

    listener:
      missing-topics-fatal: false
